"""Mapas auxiliares para transformação (geografia)."""

MAPA_ESTADOS = {
    "AL": {"nome": "ALABAMA", "regiao": "SOUTH"},
    "AK": {"nome": "ALASKA", "regiao": "WEST"},
    "AZ": {"nome": "ARIZONA", "regiao": "WEST"},
    "AR": {"nome": "ARKANSAS", "regiao": "SOUTH"},
    "CA": {"nome": "CALIFORNIA", "regiao": "WEST"},
    "CO": {"nome": "COLORADO", "regiao": "WEST"},
    "CT": {"nome": "CONNECTICUT", "regiao": "NORTHEAST"},
    "DE": {"nome": "DELAWARE", "regiao": "SOUTH"},
    "FL": {"nome": "FLORIDA", "regiao": "SOUTH"},
    "GA": {"nome": "GEORGIA", "regiao": "SOUTH"},
    "HI": {"nome": "HAWAII", "regiao": "WEST"},
    "ID": {"nome": "IDAHO", "regiao": "WEST"},
    "IL": {"nome": "ILLINOIS", "regiao": "MIDWEST"},
    "IN": {"nome": "INDIANA", "regiao": "MIDWEST"},
    "IA": {"nome": "IOWA", "regiao": "MIDWEST"},
    "KS": {"nome": "KANSAS", "regiao": "MIDWEST"},
    "KY": {"nome": "KENTUCKY", "regiao": "SOUTH"},
    "LA": {"nome": "LOUISIANA", "regiao": "SOUTH"},
    "ME": {"nome": "MAINE", "regiao": "NORTHEAST"},
    "MD": {"nome": "MARYLAND", "regiao": "SOUTH"},
    "MA": {"nome": "MASSACHUSETTS", "regiao": "NORTHEAST"},
    "MI": {"nome": "MICHIGAN", "regiao": "MIDWEST"},
    "MN": {"nome": "MINNESOTA", "regiao": "MIDWEST"},
    "MS": {"nome": "MISSISSIPPI", "regiao": "SOUTH"},
    "MO": {"nome": "MISSOURI", "regiao": "MIDWEST"},
    "MT": {"nome": "MONTANA", "regiao": "WEST"},
    "NE": {"nome": "NEBRASKA", "regiao": "MIDWEST"},
    "NV": {"nome": "NEVADA", "regiao": "WEST"},
    "NH": {"nome": "NEW HAMPSHIRE", "regiao": "NORTHEAST"},
    "NJ": {"nome": "NEW JERSEY", "regiao": "NORTHEAST"},
    "NM": {"nome": "NEW MEXICO", "regiao": "WEST"},
    "NY": {"nome": "NEW YORK", "regiao": "NORTHEAST"},
    "NC": {"nome": "NORTH CAROLINA", "regiao": "SOUTH"},
    "ND": {"nome": "NORTH DAKOTA", "regiao": "MIDWEST"},
    "OH": {"nome": "OHIO", "regiao": "MIDWEST"},
    "OK": {"nome": "OKLAHOMA", "regiao": "SOUTH"},
    "OR": {"nome": "OREGON", "regiao": "WEST"},
    "PA": {"nome": "PENNSYLVANIA", "regiao": "NORTHEAST"},
    "RI": {"nome": "RHODE ISLAND", "regiao": "NORTHEAST"},
    "SC": {"nome": "SOUTH CAROLINA", "regiao": "SOUTH"},
    "SD": {"nome": "SOUTH DAKOTA", "regiao": "MIDWEST"},
    "TN": {"nome": "TENNESSEE", "regiao": "SOUTH"},
    "TX": {"nome": "TEXAS", "regiao": "SOUTH"},
    "UT": {"nome": "UTAH", "regiao": "WEST"},
    "VT": {"nome": "VERMONT", "regiao": "NORTHEAST"},
    "VA": {"nome": "VIRGINIA", "regiao": "SOUTH"},
    "WA": {"nome": "WASHINGTON", "regiao": "WEST"},
    "WV": {"nome": "WEST VIRGINIA", "regiao": "SOUTH"},
    "WI": {"nome": "WISCONSIN", "regiao": "MIDWEST"},
    "WY": {"nome": "WYOMING", "regiao": "WEST"},
    "DC": {"nome": "DISTRICT OF COLUMBIA", "regiao": "SOUTH"},
    "PR": {"nome": "PUERTO RICO", "regiao": "TERRITORY"},
}
